apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: gotoweb           # Name of the Kubernetes resource
spec:
  replicas: 3                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: gotoweb        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: gotoweb
      annotations:
        keel.sh/policy: force
        keel.sh/trigger: poll
        keel.sh/pollSchedule: "@every 1m"
    spec:                        # Spec for the container which will run in the Pod
      containers:
        - name: gotoweb
          image: ghcr.io/patricklaabs/gotoweb
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080  # Should match the port number that the Go application listens on
          livenessProbe:           # To check the health of the Pod
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:          # To check if the Pod is ready to serve traffic or not
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: gotoweb-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9090
      targetPort: 8080
  selector:
    app: gotoweb